### ISSUE TITLE
When will the code be uploaded?

### ISSUE THREAD

**Issue by lhpqaq** [seclab-fudan/SyzDirect#1]

**Comment by Robin-Pwner** [comment]
We plan to release the code in two months.

**Comment by lhpqaq** [comment]
> We plan to release the code in two months.

Thank you for your reply

**Comment by dengnan0819** [comment]
May I get the paper now？My Email： 411407368@qq.com 
Can't wait to learn this paper

**Comment by tarasmadan** [comment]
@dengnan0819 , https://dl.acm.org/doi/abs/10.1145/3576915.3623146
This one?

**Comment by Robin-Pwner** [comment]
Hi guys, we have released the code now!
